### ISSUE TITLE
event dispatcher: IllegalArgumentException

### ISSUE THREAD

**Issue by jldec** [markfisher/sk8s#114] opened 2017-11-10 19:26 UTC
Saw this error in the event-dispatcher logs when trying the echo sample 
on master HEAD 93a5d598

```
[event-dispatcher-3155758373-hk39t] Exception in thread "Thread-2" java.lang.IllegalArgumentException: You can only check the position for partitions assigned to this consumer. 
[event-dispatcher-3155758373-hk39t] at org.apache.kafka.clients.consumer.KafkaConsumer.position(KafkaConsumer.java:1239) 
[event-dispatcher-3155758373-hk39t] at io.sk8s.event.dispatcher.KafkaConsumerMonitor.lambda$null$5(KafkaConsumerMonitor.java:112) 
[event-dispatcher-3155758373-hk39t] at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) 
[event-dispatcher-3155758373-hk39t] at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) 
[event-dispatcher-3155758373-hk39t] at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) 
[event-dispatcher-3155758373-hk39t] at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) 
[event-dispatcher-3155758373-hk39t] at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) 
[event-dispatcher-3155758373-hk39t] at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) 
[event-dispatcher-3155758373-hk39t] at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) 
[event-dispatcher-3155758373-hk39t] at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) 
[event-dispatcher-3155758373-hk39t] at io.sk8s.event.dispatcher.KafkaConsumerMonitor.lambda$compute$6(KafkaConsumerMonitor.java:116) 
[event-dispatcher-3155758373-hk39t] at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1321) 
[event-dispatcher-3155758373-hk39t] at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) 
[event-dispatcher-3155758373-hk39t] at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1548) 
[event-dispatcher-3155758373-hk39t] at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) 
[event-dispatcher-3155758373-hk39t] at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) 
[event-dispatcher-3155758373-hk39t] at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) 
[event-dispatcher-3155758373-hk39t] at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) 
[event-dispatcher-3155758373-hk39t] at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) 
[event-dispatcher-3155758373-hk39t] at io.sk8s.event.dispatcher.KafkaConsumerMonitor.compute(KafkaConsumerMonitor.java:100) 
[event-dispatcher-3155758373-hk39t] at io.sk8s.event.dispatcher.EventDispatchingHandler$ScalingMonitor.run(EventDispatchingHandler.java:161) 
[event-dispatcher-3155758373-hk39t] at java.lang.Thread.run(Thread.java:745) 
```

**Comment by markfisher** [comment] 2017-11-10 20:48
I was discussing this earlier with Eric. There seems to be a discrepancy when we assign partitions to the consumer in `reassignPartitions()`. Locally I've added this temporary fix which I can go ahead and push until we have a better sense of how to handle it proactively:

```
long position = 0;
try {
	position = logEndOffsetTrackingConsumer.position(tp);
}
catch (IllegalArgumentException e) {
	logEndOffsetTrackingConsumer.assign(Collections.singleton(tp));
	position = logEndOffsetTrackingConsumer.position(tp);
}
```

**Comment by ericbottard** [comment] 2017-11-10 21:15
Synchronizing the lag monitor should dix it

**Comment by markfisher** [comment] 2017-11-11 14:29
@ericbottard can you indicate the scope (code line/block) of what needs to be synchronized?

**Comment by ericbottard** [comment] 2017-11-12 16:12
Hmm, embarrassing, I already did this ([here](https://github.com/markfisher/sk8s/blob/3c8619424502f0977e8417dfe14b5b0d9144b4e2/event-dispatcher/src/main/java/io/sk8s/event/dispatcher/EventDispatchingHandler.java#L158)).

This should not happen as `reassignPartitions` can't happen in the middle of computation. I wonder though, if this happens when consumers (ie functions) change. Would be nice to have a consistent way of reproducing, as always...

**Comment by markfisher** [comment] 2017-11-12 16:17
but the `reassingPartitions` call is synchronized on the `KafkaConsumerMonitor` right?

**Comment by ericbottard** [comment] 2017-11-12 16:20
Yes, but that's because it needs to be synchronized with `close()` there.

It is syncrhonized on the EventDispatcher through a coarser grained scope (namely function added, removed and the Runnable method)

**Comment by markfisher** [comment] 2017-11-14 16:10
assigned you @ericbottard but happy to collaborate

**Closed** 2017-11-15 18:42 UTC
